#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
#  বাঙালি ইসলামিক ইনস্টিটিউট — One-command cPanel Setup
#  Run once from cPanel Terminal after extracting the ZIP:
#      bash ~/public_html/setup.sh
# ═══════════════════════════════════════════════════════════════════

set -e

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$APP_DIR"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Bengali Islamic Institute — Automated cPanel Setup"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# ── Step 1: Find and activate the cPanel virtual environment ─────────────────
echo "🔍 Looking for cPanel virtual environment..."
VENV_ACTIVATED=false
PYTHON_BIN="python3"
PIP_BIN="pip3"

for venv_path in \
    ~/virtualenv/public_html/3.11/bin/activate \
    ~/virtualenv/public_html/3.10/bin/activate \
    ~/virtualenv/public_html/3.9/bin/activate \
    ~/virtualenv/public_html/3.8/bin/activate; do
    if [ -f "$venv_path" ]; then
        source "$venv_path"
        PYTHON_BIN="python"
        PIP_BIN="pip"
        VENV_ACTIVATED=true
        echo "✅ Activated: $venv_path"
        break
    fi
done

# Also check for version in any subdirectory name
if [ "$VENV_ACTIVATED" = false ]; then
    for venv_dir in ~/virtualenv/public_html/*/; do
        if [ -f "${venv_dir}bin/activate" ]; then
            source "${venv_dir}bin/activate"
            PYTHON_BIN="python"
            PIP_BIN="pip"
            VENV_ACTIVATED=true
            echo "✅ Activated: ${venv_dir}"
            break
        fi
    done
fi

if [ "$VENV_ACTIVATED" = false ]; then
    echo ""
    echo "⚠️  WARNING: Could not find cPanel virtual environment."
    echo "   This usually means the Python App has not been created in cPanel yet."
    echo "   Please create it first (see README), then run this script again."
    echo ""
    echo "   After creating the Python App, run:"
    echo "   bash ~/public_html/setup.sh"
    echo ""
    exit 1
fi

PYTHON_VERSION=$($PYTHON_BIN --version 2>&1)
echo "   Python: $PYTHON_VERSION"
echo ""

# ── Step 2: Install Python packages ──────────────────────────────────────────
echo "📦 Installing Python packages (this takes 1–3 minutes)..."
$PIP_BIN install -r "$APP_DIR/requirements_prod.txt" -q --no-warn-script-location
echo "✅ Packages installed"
echo ""

# ── Step 3: Configure environment (.env) ─────────────────────────────────────
if [ -f "$APP_DIR/.env" ]; then
    echo "ℹ️  .env file already exists — skipping configuration."
    echo "   To reconfigure, delete .env and run this script again."
    echo ""
else
    echo "📝 Let's configure your website. You need 4 things:"
    echo "   1. MongoDB Atlas connection string"
    echo "   2. Your website domain"
    echo "   3. Admin email address"
    echo "   4. Admin password"
    echo ""
    echo "   (JWT secret is generated automatically — you do not need to provide one)"
    echo ""

    # ── MongoDB URL ────────────────────────────────────────────────────────
    while true; do
        echo -n "① MongoDB connection string (mongodb+srv://...): "
        read -r MONGODB_URL
        if echo "$MONGODB_URL" | grep -q "mongodb"; then
            break
        else
            echo "   ❌ That doesn't look right. It should start with 'mongodb+srv://' or 'mongodb://'"
        fi
    done

    # ── Site URL ───────────────────────────────────────────────────────────
    while true; do
        echo -n "② Your domain (e.g. https://yourdomain.com): "
        read -r SITE_URL
        SITE_URL="${SITE_URL%/}"   # strip trailing slash
        if echo "$SITE_URL" | grep -q "http"; then
            break
        else
            echo "   ❌ Please include http:// or https:// (e.g. https://yourdomain.com)"
        fi
    done

    # ── Admin Email ────────────────────────────────────────────────────────
    while true; do
        echo -n "③ Admin email address: "
        read -r ADMIN_EMAIL
        if echo "$ADMIN_EMAIL" | grep -q "@"; then
            break
        else
            echo "   ❌ Please enter a valid email address"
        fi
    done

    # ── Admin Password ─────────────────────────────────────────────────────
    while true; do
        echo -n "④ Admin password (min 8 characters): "
        read -r ADMIN_PASSWORD
        if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
            break
        else
            echo "   ❌ Password must be at least 8 characters"
        fi
    done

    # ── Auto-generate JWT_SECRET ───────────────────────────────────────────
    JWT_SECRET=$($PYTHON_BIN -c "import secrets; print(secrets.token_hex(48))")
    echo ""
    echo "🔑 JWT secret auto-generated ✓"

    # ── Write .env ─────────────────────────────────────────────────────────
    cat > "$APP_DIR/.env" << ENVEOF
# Generated by setup.sh on $(date)
# Do not share this file — it contains secrets

# ── Required ──────────────────────────────────────────────────────────────────
MONGODB_URL=${MONGODB_URL}
JWT_SECRET=${JWT_SECRET}
SITE_URL=${SITE_URL}
CORS_ORIGINS=${SITE_URL}

# ── Database ──────────────────────────────────────────────────────────────────
DB_NAME=bii_db

# ── Admin account (used only on first startup) ────────────────────────────────
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_NAME=Super Admin

# ── Application ───────────────────────────────────────────────────────────────
APP_NAME=bii
APP_VERSION=1.0.0
INSTITUTE_NAME_BN=বাঙালি ইসলামিক ইনস্টিটিউট
INSTITUTE_NAME_EN=Bengali Islamic Institute

# ── Optional — fill in later from Admin Panel if needed ──────────────────────
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
APP_MIN_VERSION=1.0.0
APP_FORCE_UPDATE=false
ENVEOF

    echo "✅ .env created"
    echo ""
fi

# ── Step 4: Set permissions ───────────────────────────────────────────────────
echo "🔒 Setting directory permissions..."
mkdir -p "$APP_DIR/uploads"
chmod 755 "$APP_DIR/uploads"
echo "✅ uploads/ → 755"
echo ""

# ── Step 5: Try to restart Passenger via cPanel UAPI ─────────────────────────
echo "🔄 Restarting Python app..."
RESTART_OK=false

# Method A: uapi (cPanel command-line API — available in most cPanel Terminal sessions)
if command -v uapi &> /dev/null 2>&1; then
    uapi PythonApp restart_application application_root=public_html > /dev/null 2>&1 && \
        RESTART_OK=true && echo "✅ App restarted via UAPI"
fi

# Method B: touch passenger_wsgi.py (forces Passenger to reload in most setups)
if [ "$RESTART_OK" = false ]; then
    touch "$APP_DIR/passenger_wsgi.py"
    RESTART_OK=true
    echo "✅ Passenger reload triggered (touch passenger_wsgi.py)"
fi

echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo "═══════════════════════════════════════════════════════════════"
echo "  ✅ Setup complete!"
echo ""
if [ -f "$APP_DIR/.env" ]; then
    DOMAIN=$(grep "^SITE_URL=" "$APP_DIR/.env" | cut -d= -f2)
    echo "  🌐 Your website:  $DOMAIN"
    echo "  🔐 Admin login:   $DOMAIN/login"
    echo "  📊 API health:    $DOMAIN/api/health"
fi
echo ""
echo "  If the site doesn't load yet, go to cPanel → Setup Python App"
echo "  and click the Restart button."
echo ""
echo "  MongoDB tip: if the site shows a database error, add your"
echo "  server's IP to MongoDB Atlas → Network Access → Add IP Address."
echo "═══════════════════════════════════════════════════════════════"
echo ""
